
// Tattoo layer defines
#define CUSTOM_TATTOO_LAYER_UNDER 1
#define CUSTOM_TATTOO_LAYER_NORMAL 2
#define CUSTOM_TATTOO_LAYER_OVER 3

// Tattoo preference path
#define CUSTOM_TATTOO_PREFERENCE_PATH /datum/preference/toggle/allow_bodywriting

// Maximum tattoos per body part - CHANGED TO 3
#define CUSTOM_MAX_TATTOOS_PER_PART 3

// Default tattoo application time
#define CUSTOM_TATTOO_APPLICATION_TIME (8 SECONDS)

// Tattooable organ slots
#define CUSTOM_TATTOOABLE_ORGAN_SLOTS list(\
	ORGAN_SLOT_PENIS,\
	ORGAN_SLOT_WOMB,\
	ORGAN_SLOT_VAGINA,\
	ORGAN_SLOT_TESTICLES,\
	ORGAN_SLOT_BREASTS,\
	ORGAN_SLOT_ANUS,\
	ORGAN_SLOT_NIPPLES,\
	ORGAN_SLOT_TAIL,\
	ORGAN_SLOT_SLIT,\
	ORGAN_SLOT_SHEATH,\
	ORGAN_SLOT_WINGS,\
	ORGAN_SLOT_BUTT,\
	ORGAN_SLOT_BELLY\
)

// Custom tattoo fonts (must match client font options if you add any)
GLOBAL_LIST_INIT(custom_tattoo_fonts, list(
	PEN_FONT,
	FOUNTAIN_PEN_FONT,
	CRAYON_FONT,
	PRINTER_FONT,
	CHARCOAL_FONT
))

// Safe span classes that can be used in examine text
GLOBAL_LIST_INIT(safe_span_classes, list(
	"pink",
	"userlove",
	"brown",
	"cyan",
	"orange",
	"yellow",
	"subtle",
	"velvet",
	"velvet_notice",
	"glossy"
))

// Custom tattoo flairs (text-based formatting)
GLOBAL_LIST_INIT(custom_tattoo_flairs, list(
	"flair_1" = "pink",
	"flair_2" = "userlove",
	"flair_3" = "brown",
	"flair_4" = "cyan",
	"flair_5" = "orange",
	"flair_6" = "yellow",
	"flair_7" = "subtle",
	"flair_8" = "velvet",
	"flair_9" = "velvet_notice",
	"flair_10" = "glossy"
))

// Global text-based emoji mappings
GLOBAL_LIST_INIT(text_emoji_mappings, list(
	":smile:" = "☺",
	":sad:" = "☹",
	":heart:" = "♥",
	":star:" = "★",
	":spade:" = "♠",
	":club:" = "♣",
	":diamond:" = "♦",
	":music:" = "♪",
	":sun:" = "☀",
	":cloud:" = "☁",
	":rain:" = "☔",
	":snow:" = "❄",
	":phone:" = "☎",
	":mail:" = "✉",
	":pencil:" = "✏",
	":scissors:" = "✂",
	":check:" = "✓",
	":x:" = "✗",
	":warning:" = "⚠",
	":radioactive:" = "☢",
	":biohazard:" = "☣",
	":peace:" = "☮",
	":yin_yang:" = "☯",
	":wheelchair:" = "♿",
	":recycle:" = "♻",
	":tm:" = "™",
	":copyright:" = "©",
	":registered:" = "®",
	":skull:" = "☠",
	":anchor:" = "⚓",
	":umbrella:" = "☂",
	":snowman:" = "☃",
	":coffee:" = "☕",
	":fire:" = "🔥",
	":thumbsup:" = "👍",
	":thumbsdown:" = "👎",
	":ok_hand:" = "👌",
	":v:" = "✌",
	":clap:" = "👏",
	":pray:" = "🙏",
	":eyes:" = "👀",
	":eye:" = "👁",
	":ear:" = "👂",
	":nose:" = "👃",
	":lips:" = "👄",
	":tongue:" = "👅",
	":wave:" = "👋",
	":raised_hand:" = "✋",
	":open_hands:" = "👐",
	":point_up:" = "☝",
	":point_down:" = "👇",
	":point_left:" = "👈",
	":point_right:" = "👉",
	":middle_finger:" = "🖕",
	":fist:" = "✊",
	":raised_fist:" = "✊",
	":vulcan:" = "🖖",
	":writing_hand:" = "✍",
	":pencil2:" = "✏",
	":black_heart:" = "🖤",
	":blue_heart:" = "💙",
	":green_heart:" = "💚",
	":yellow_heart:" = "💛",
	":purple_heart:" = "💜",
	":broken_heart:" = "💔",
	":heartbeat:" = "💓",
	":sparkling_heart:" = "💖",
	":star2:" = "⭐",
	":dizzy:" = "💫",
	":boom:" = "💥",
	":zzz:" = "💤",
	":sweat_drops:" = "💦",
	":droplet:" = "💧",
	":muscle:" = "💪",
	":footprints:" = "👣",
	":brain:" = "🧠",
	":bone:" = "🦴",
	":tooth:" = "🦷",
	":alien:" = "👽",
	":robot:" = "🤖",
	":poop:" = "💩",
	":ghost:" = "👻",
	":japanese_goblin:" = "👺",
	":japanese_ogre:" = "👹",
	":angel:" = "👼",
	":imp:" = "👿",
	":skull_crossbones:" = "☠",
	":snake:" = "🐍",
	":spider:" = "🕷",
	":bat:" = "🦇",
	":bear:" = "🐻",
	":bird:" = "🐦",
	":cat:" = "🐱",
	":dog:" = "🐶",
	":fox:" = "🦊",
	":lion:" = "🦁",
	":tiger:" = "🐯",
	":wolf:" = "🐺",
	":horse:" = "🐴",
	":unicorn:" = "🦄",
	":cow:" = "🐮",
	":pig:" = "🐷",
	":frog:" = "🐸",
	":monkey:" = "🐵",
	":chicken:" = "🐔",
	":penguin:" = "🐧",
	":fish:" = "🐟",
	":whale:" = "🐳",
	":dolphin:" = "🐬",
	":octopus:" = "🐙",
	":butterfly:" = "🦋",
	":bee:" = "🐝",
	":ant:" = "🐜",
	":ladybug:" = "🐞",
	":turtle:" = "🐢",
	":snail:" = "🐌",
	":dragon:" = "🐉",
	":dragon_face:" = "🐲",
	":cactus:" = "🌵",
	":tree:" = "🌳",
	":four_leaf_clover:" = "🍀",
	":herb:" = "🌿",
	":maple_leaf:" = "🍁",
	":fallen_leaf:" = "🍂",
	":leaves:" = "🍃",
	":mushroom:" = "🍄",
	":ear_of_rice:" = "🌾",
	":bouquet:" = "💐",
	":tulip:" = "🌷",
	":rose:" = "🌹",
	":sunflower:" = "🌻",
	":blossom:" = "🌼",
	":cherry_blossom:" = "🌸",
	":hibiscus:" = "🌺",
	":earth_americas:" = "🌎",
	":earth_africa:" = "🌍",
	":earth_asia:" = "🌏",
	":full_moon:" = "🌕",
	":sun_with_face:" = "🌞",
	":star:" = "⭐",
	":globe:" = "🌐",
	":volcano:" = "🌋",
	":mount_fuji:" = "🗻",
	":house:" = "🏠",
	":church:" = "⛪",
	":office:" = "🏢",
	":hospital:" = "🏥",
	":bank:" = "🏦",
	":hotel:" = "🏨",
	":love_hotel:" = "🏩",
	":convenience_store:" = "🏪",
	":school:" = "🏫",
	":department_store:" = "🏬",
	":factory:" = "🏭",
	":japanese_castle:" = "🏯",
	":european_castle:" = "🏰",
	":rainbow:" = "🌈",
	":fireworks:" = "🎆",
	":sparkler:" = "🎇",
	":rice_scene:" = "🎑",
	":jack_o_lantern:" = "🎃",
	":christmas_tree:" = "🎄",
	":santa:" = "🎅",
	":angel:" = "👼",
	":sparkles:" = "✨",
	":balloon:" = "🎈",
	":tada:" = "🎉",
	":confetti_ball:" = "🎊",
	":tanabata_tree:" = "🎋",
	":crossed_flags:" = "🎌",
	":bamboo:" = "🎍",
	":dolls:" = "🎎",
	":flags:" = "🎏",
	":wind_chime:" = "🎐",
	":ribbon:" = "🎀",
	":gift:" = "🎁",
	":reminder_ribbon:" = "🎗",
	":tickets:" = "🎟",
	":ticket:" = "🎫",
	":medal:" = "🎖",
	":trophy:" = "🏆",
	":sports_medal:" = "🏅",
	":first_place:" = "🥇",
	":second_place:" = "🥈",
	":third_place:" = "🥉",
	":soccer:" = "⚽",
	":baseball:" = "⚾",
	":basketball:" = "🏀",
	":volleyball:" = "🏐",
	":football:" = "🏈",
	":rugby_football:" = "🏉",
	":tennis:" = "🎾",
	":8ball:" = "🎱",
	":bowling:" = "🎳",
	":cricket:" = "🏏",
	":field_hockey:" = "🏑",
	":ice_hockey:" = "🏒",
	":ping_pong:" = "🏓",
	":badminton:" = "🏸",
	":boxing_glove:" = "🥊",
	":martial_arts_uniform:" = "🥋",
	":goal:" = "🥅",
	":dart:" = "🎯",
	":golf:" = "⛳",
	":ice_skate:" = "⛸",
	":fishing_pole:" = "🎣",
	":running_shirt:" = "🎽",
	":ski:" = "🎿",
	":sled:" = "🛷",
	":curling_stone:" = "🥌",
	":video_game:" = "🎮",
	":joystick:" = "🕹",
	":game_die:" = "🎲",
	":chess_pawn:" = "♟",
	":dart:" = "🎯",
	":bow_and_arrow:" = "🏹",
	":water_pistol:" = "🔫",
	":bomb:" = "💣",
	":knife:" = "🔪",
	":dagger:" = "🗡",
	":crossed_swords:" = "⚔",
	":shield:" = "🛡",
	":smoking:" = "🚬",
	":coffin:" = "⚰",
	":funeral_urn:" = "⚱",
	":amphora:" = "🏺",
	":crystal_ball:" = "🔮",
	":prayer_beads:" = "📿",
	":nazar_amulet:" = "🧿",
	":barber:" = "💈",
	":alembic:" = "⚗",
	":telescope:" = "🔭",
	":microscope:" = "🔬",
	":hole:" = "🕳",
	":pill:" = "💊",
	":syringe:" = "💉",
	":dna:" = "🧬",
	":microbe:" = "🦠",
	":test_tube:" = "🧪",
	":petri_dish:" = "🧫",
	":thermometer:" = "🌡",
	":broom:" = "🧹",
	":basket:" = "🧺",
	":roll_of_paper:" = "🧻",
	":soap:" = "🧼",
	":sponge:" = "🧽",
	":fire_extinguisher:" = "🧯",
	":shopping_cart:" = "🛒",
	":smiley:" = "😃",
	":smile:" = "😄",
	":grin:" = "😁",
	":laughing:" = "😆",
	":sweat_smile:" = "😅",
	":rofl:" = "🤣",
	":joy:" = "😂",
	":slightly_smiling:" = "🙂",
	":upside_down:" = "🙃",
	":wink:" = "😉",
	":blush:" = "😊",
	":innocent:" = "😇",
	":heart_eyes:" = "😍",
	":kissing_heart:" = "😘",
	":kissing:" = "😗",
	":relaxed:" = "☺",
	":kissing_closed_eyes:" = "😚",
	":kissing_smiling_eyes:" = "😙",
	":yum:" = "😋",
	":stuck_out_tongue:" = "😛",
	":stuck_out_tongue_winking_eye:" = "😜",
	":stuck_out_tongue_closed_eyes:" = "😝",
	":money_mouth:" = "🤑",
	":hugs:" = "🤗",
	":thinking:" = "🤔",
	":zipper_mouth:" = "🤐",
	":raised_eyebrow:" = "🤨",
	":neutral:" = "😐",
	":expressionless:" = "😑",
	":no_mouth:" = "😶",
	":smirk:" = "😏",
	":unamused:" = "😒",
	":roll_eyes:" = "🙄",
	":grimacing:" = "😬",
	":lying:" = "🤥",
	":relieved:" = "😌",
	":pensive:" = "😔",
	":sleepy:" = "😪",
	":drooling:" = "🤤",
	":sleeping:" = "😴",
	":mask:" = "😷",
	":face_with_thermometer:" = "🤒",
	":face_with_head_bandage:" = "🤕",
	":nauseated:" = "🤢",
	":vomiting:" = "🤮",
	":sneezing:" = "🤧",
	":hot:" = "🥵",
	":cold:" = "🥶",
	":woozy:" = "🥴",
	":dizzy:" = "😵",
	":exploding_head:" = "🤯",
	":cowboy:" = "🤠",
	":partying:" = "🥳",
	":disguised:" = "🥸",
	":sunglasses:" = "😎",
	":nerd:" = "🤓",
	":monocle:" = "🧐",
	":confused:" = "😕",
	":worried:" = "😟",
	":slightly_frowning:" = "🙁",
	":frowning:" = "☹",
	":open_mouth:" = "😮",
	":hushed:" = "😯",
	":astonished:" = "😲",
	":flushed:" = "😳",
	":pleading:" = "🥺",
	":frowning2:" = "😦",
	":anguished:" = "😧",
	":fearful:" = "😨",
	":cold_sweat:" = "😰",
	":disappointed_relieved:" = "😥",
	":cry:" = "😢",
	":sob:" = "😭",
	":scream:" = "😱",
	":confounded:" = "😖",
	":persevere:" = "😣",
	":disappointed:" = "😞",
	":sweat:" = "😓",
	":weary:" = "😩",
	":tired:" = "😫",
	":yawning:" = "🥱",
	":triumph:" = "😤",
	":rage:" = "😡",
	":pout:" = "😡",
	":angry:" = "😠",
	":cursing:" = "🤬",
	":smiling_imp:" = "😈",
	":imp:" = "👿",
	":skull:" = "💀",
	":skull_crossbones:" = "☠",
	":hankey:" = "💩",
	":clown:" = "🤡",
	":japanese_ogre:" = "👹",
	":japanese_goblin:" = "👺",
	":ghost:" = "👻",
	":alien:" = "👽",
	":robot:" = "🤖",
	":smiley_cat:" = "😺",
	":smile_cat:" = "😸",
	":joy_cat:" = "😹",
	":heart_eyes_cat:" = "😻",
	":smirk_cat:" = "😼",
	":kissing_cat:" = "😽",
	":scream_cat:" = "🙀",
	":crying_cat_face:" = "😿",
	":pouting_cat:" = "😾"
))
